version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: tturkowski/fruits-and-vegetables
    container_name: roadsurfer_php
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - roadsurfer_net
    env_file:
      - app/.env
    depends_on:
      - mysql
    tty: true
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: roadsurfer_nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - roadsurfer_net

  mysql:
    image: mysql:8.0
    container_name: roadsurfer_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: roadsurfer_db
      MYSQL_USER: roadsurfer_user
      MYSQL_PASSWORD: roadsurfer_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - roadsurfer_net
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  roadsurfer_net:
    driver: bridge
